/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as MovieSlugRouteImport } from './routes/movie.$slug'
import { Route as UsersDashboardRouteImport } from './routes/users/dashboard'
import { Route as WatchIndexRouteImport } from './routes/watch.index'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AuthenticatedAccountActivityRouteImport } from './routes/_authenticated/account.activity'
import { Route as AuthenticatedAccountDownloadsRouteImport } from './routes/_authenticated/account.downloads'
import { Route as AuthenticatedAccountFeedbackRouteImport } from './routes/_authenticated/account.feedback'
import { Route as AuthenticatedAccountHistoryRouteImport } from './routes/_authenticated/account.history'
import { Route as AuthenticatedAccountMessagesRouteImport } from './routes/_authenticated/account.messages'
import { Route as AuthenticatedAccountPremiumRouteImport } from './routes/_authenticated/account.premium'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account.profile'
import { Route as AuthenticatedAccountRewardsRouteImport } from './routes/_authenticated/account.rewards'
import { Route as AuthenticatedAccountSettingsRouteImport } from './routes/_authenticated/account.settings'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin.$id'
import { Route as AuthenticatedAdminNewRouteImport } from './routes/_authenticated/admin.new'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin.providers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MovieSlugRoute = MovieSlugRouteImport.update({
  id: '/movie/$slug',
  path: '/movie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersDashboardRoute = UsersDashboardRouteImport.update({
  id: '/users/dashboard',
  path: '/users/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIndexRoute = WatchIndexRouteImport.update({
  id: '/watch/',
  path: '/watch/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountActivityRoute =
  AuthenticatedAccountActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountDownloadsRoute =
  AuthenticatedAccountDownloadsRouteImport.update({
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountFeedbackRoute =
  AuthenticatedAccountFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountHistoryRoute =
  AuthenticatedAccountHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountMessagesRoute =
  AuthenticatedAccountMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountPremiumRoute =
  AuthenticatedAccountPremiumRouteImport.update({
    id: '/premium',
    path: '/premium',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountRewardsRoute =
  AuthenticatedAccountRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountSettingsRoute =
  AuthenticatedAccountSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNewRoute = AuthenticatedAdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/users/dashboard': typeof UsersDashboardRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/watch/': typeof WatchIndexRoute
  '/account/activity': typeof AuthenticatedAccountActivityRoute
  '/account/downloads': typeof AuthenticatedAccountDownloadsRoute
  '/account/feedback': typeof AuthenticatedAccountFeedbackRoute
  '/account/history': typeof AuthenticatedAccountHistoryRoute
  '/account/messages': typeof AuthenticatedAccountMessagesRoute
  '/account/premium': typeof AuthenticatedAccountPremiumRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/rewards': typeof AuthenticatedAccountRewardsRoute
  '/account/settings': typeof AuthenticatedAccountSettingsRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/users/dashboard': typeof UsersDashboardRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/watch': typeof WatchIndexRoute
  '/account/activity': typeof AuthenticatedAccountActivityRoute
  '/account/downloads': typeof AuthenticatedAccountDownloadsRoute
  '/account/feedback': typeof AuthenticatedAccountFeedbackRoute
  '/account/history': typeof AuthenticatedAccountHistoryRoute
  '/account/messages': typeof AuthenticatedAccountMessagesRoute
  '/account/premium': typeof AuthenticatedAccountPremiumRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/rewards': typeof AuthenticatedAccountRewardsRoute
  '/account/settings': typeof AuthenticatedAccountSettingsRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/users/dashboard': typeof UsersDashboardRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/watch/': typeof WatchIndexRoute
  '/_authenticated/account/activity': typeof AuthenticatedAccountActivityRoute
  '/_authenticated/account/downloads': typeof AuthenticatedAccountDownloadsRoute
  '/_authenticated/account/feedback': typeof AuthenticatedAccountFeedbackRoute
  '/_authenticated/account/history': typeof AuthenticatedAccountHistoryRoute
  '/_authenticated/account/messages': typeof AuthenticatedAccountMessagesRoute
  '/_authenticated/account/premium': typeof AuthenticatedAccountPremiumRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/rewards': typeof AuthenticatedAccountRewardsRoute
  '/_authenticated/account/settings': typeof AuthenticatedAccountSettingsRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/new': typeof AuthenticatedAdminNewRoute
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/account'
    | '/admin'
    | '/watchlist'
    | '/movie/$slug'
    | '/users/dashboard'
    | '/watch/$slug'
    | '/watch/'
    | '/account/activity'
    | '/account/downloads'
    | '/account/feedback'
    | '/account/history'
    | '/account/messages'
    | '/account/premium'
    | '/account/profile'
    | '/account/rewards'
    | '/account/settings'
    | '/admin/$id'
    | '/admin/new'
    | '/admin/providers'
    | '/account/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/watchlist'
    | '/movie/$slug'
    | '/users/dashboard'
    | '/watch/$slug'
    | '/watch'
    | '/account/activity'
    | '/account/downloads'
    | '/account/feedback'
    | '/account/history'
    | '/account/messages'
    | '/account/premium'
    | '/account/profile'
    | '/account/rewards'
    | '/account/settings'
    | '/admin/$id'
    | '/admin/new'
    | '/admin/providers'
    | '/account'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/watchlist'
    | '/movie/$slug'
    | '/users/dashboard'
    | '/watch/$slug'
    | '/watch/'
    | '/_authenticated/account/activity'
    | '/_authenticated/account/downloads'
    | '/_authenticated/account/feedback'
    | '/_authenticated/account/history'
    | '/_authenticated/account/messages'
    | '/_authenticated/account/premium'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/rewards'
    | '/_authenticated/account/settings'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/new'
    | '/_authenticated/admin/providers'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  MovieSlugRoute: typeof MovieSlugRoute
  UsersDashboardRoute: typeof UsersDashboardRoute
  WatchSlugRoute: typeof WatchSlugRoute
  WatchIndexRoute: typeof WatchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/movie/$slug': {
      id: '/movie/$slug'
      path: '/movie/$slug'
      fullPath: '/movie/$slug'
      preLoaderRoute: typeof MovieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/dashboard': {
      id: '/users/dashboard'
      path: '/users/dashboard'
      fullPath: '/users/dashboard'
      preLoaderRoute: typeof UsersDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/': {
      id: '/watch/'
      path: '/watch'
      fullPath: '/watch/'
      preLoaderRoute: typeof WatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/activity': {
      id: '/_authenticated/account/activity'
      path: '/activity'
      fullPath: '/account/activity'
      preLoaderRoute: typeof AuthenticatedAccountActivityRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/downloads': {
      id: '/_authenticated/account/downloads'
      path: '/downloads'
      fullPath: '/account/downloads'
      preLoaderRoute: typeof AuthenticatedAccountDownloadsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/feedback': {
      id: '/_authenticated/account/feedback'
      path: '/feedback'
      fullPath: '/account/feedback'
      preLoaderRoute: typeof AuthenticatedAccountFeedbackRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/history': {
      id: '/_authenticated/account/history'
      path: '/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AuthenticatedAccountHistoryRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/messages': {
      id: '/_authenticated/account/messages'
      path: '/messages'
      fullPath: '/account/messages'
      preLoaderRoute: typeof AuthenticatedAccountMessagesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/premium': {
      id: '/_authenticated/account/premium'
      path: '/premium'
      fullPath: '/account/premium'
      preLoaderRoute: typeof AuthenticatedAccountPremiumRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/rewards': {
      id: '/_authenticated/account/rewards'
      path: '/rewards'
      fullPath: '/account/rewards'
      preLoaderRoute: typeof AuthenticatedAccountRewardsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/settings': {
      id: '/_authenticated/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AuthenticatedAccountSettingsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/new': {
      id: '/_authenticated/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AuthenticatedAdminNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountActivityRoute: typeof AuthenticatedAccountActivityRoute
  AuthenticatedAccountDownloadsRoute: typeof AuthenticatedAccountDownloadsRoute
  AuthenticatedAccountFeedbackRoute: typeof AuthenticatedAccountFeedbackRoute
  AuthenticatedAccountHistoryRoute: typeof AuthenticatedAccountHistoryRoute
  AuthenticatedAccountMessagesRoute: typeof AuthenticatedAccountMessagesRoute
  AuthenticatedAccountPremiumRoute: typeof AuthenticatedAccountPremiumRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountRewardsRoute: typeof AuthenticatedAccountRewardsRoute
  AuthenticatedAccountSettingsRoute: typeof AuthenticatedAccountSettingsRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountActivityRoute: AuthenticatedAccountActivityRoute,
  AuthenticatedAccountDownloadsRoute: AuthenticatedAccountDownloadsRoute,
  AuthenticatedAccountFeedbackRoute: AuthenticatedAccountFeedbackRoute,
  AuthenticatedAccountHistoryRoute: AuthenticatedAccountHistoryRoute,
  AuthenticatedAccountMessagesRoute: AuthenticatedAccountMessagesRoute,
  AuthenticatedAccountPremiumRoute: AuthenticatedAccountPremiumRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountRewardsRoute: AuthenticatedAccountRewardsRoute,
  AuthenticatedAccountSettingsRoute: AuthenticatedAccountSettingsRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminNewRoute: typeof AuthenticatedAdminNewRoute
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminNewRoute: AuthenticatedAdminNewRoute,
  AuthenticatedAdminProvidersRoute: AuthenticatedAdminProvidersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  MovieSlugRoute: MovieSlugRoute,
  UsersDashboardRoute: UsersDashboardRoute,
  WatchSlugRoute: WatchSlugRoute,
  WatchIndexRoute: WatchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
